all:
	./build_tiapp.sh

clean:
	rm -f comp512st/paxos/utils/*.class comp512st/paxos/*.class comp512st/tests/*.class comp512st/tiapp/*.class
	rm -f comp512st/tiapp/*.log
	rm -f comp512st/tests/*.log